### PR TITLE
Added custom output formatting, multi-word commands

### PR DESCRIPTION
**Pull request by ewels**
Hi there,

Many thanks for creating this, it's great! Much nicer than some of the other bigger packages which require `sudo` and all sorts, this got me running on a remote server in minutes.

I've been running the [C++ tldr client](https://github.com/tldr-pages/tldr-cpp-client) for a while now and have gotten pretty use to those colours and styles. This pull-request makes the styling configurable if certain environment variables are set (falling back to your previous defaults).

I also patched up the readme file a fraction with some more GitHub-flavoured markdown (eg. code syntax highlighting). Note that the repo name `tldr` clashed for me because the [main repository](https://github.com/tldr-pages/tldr) has the same name. So I renamed my fork to `tldr-bash`.

Let me know if you'd like me to change anything!

Phil

### CODE REVIEW

**Comment by ewels** [comment]
Just pushed a second small commit to add support for some of the commands that have spaces in them, such as `$ tldr git commit`. It simply switches the spaces in any unrecognised arguments into hyphens.

**Comment by ewels** [comment]
Also, I spent ages messing around trying to get multi-word formatting strings to work (for example `italic yellow`), but eventually gave up as I was going around in circles. My bash skills are pretty weak - if you can think of a nice way to do this then that would also be great!

**Comment by raylee** [comment]
Thanks! I'm going to work through my open PRs in order, but wanted you to know I like these changes. I'll see if I can get the multi-word formatting to work as well.

**Comment by ewels** [comment]
Ok great, thanks for letting me know :) Shout if any merge conflicts turn up from other updates that you'd like me to fix too..

**Comment by j8r** [comment]
@ewels I agree with you to change name of the project, `tldr.sh` can be good.
I hope @raylee will merge my PR soon so you can solve the conflicts, thank you for your work and sorry in advance!
The project will become POSIX compliant to support most of shells on a wide range of systems. Be sure to try with `bash --posix` or `dash` on debian. Don't worry this isn't as much compticated to comply.
By the way we will need to add details on contributing docs.

**Comment by waldyrious** [comment]
> @ewels I agree with you to change name of the project, `tldr.sh` can be good.

@j8r just to keep you in the loop, you probably should take a look at the conversation starting at https://github.com/tldr-pages/tldr/issues/1109#issuecomment-255104786

**Comment by raylee** [comment]
Hey there,

I've been working two jobs (startup and another to pay the bills), and haven't had the energy to touch a computer in off hours. Not to mention wanting to have a life outside of an office. Could you double-check this PR and check if you're still happy with the request?

Thanks!

**Comment by ewels** [comment]
Hi @raylee!

I’d kind of forgotten this PR to be honest, but I’ve been happily using my fork for all of this time with no troubles, so yes I’m still happy :)

Phil

**Comment by ewels** [comment]
Fixed another merge conflict, just in case.. 😇

**Comment by raylee** [comment]
Thank you. I'm on the road for the next four days but will give this all a fresh review Monday or Tuesday.

**Comment by raylee** [comment]
I made a couple minor changes to your PR. I renamed under -> underline now that it's a user-visible option, so if you're using 'under' as an option you'll want to update that. Multiple style options can be set now, eg `export TLDR_HEADER="magenta bold italic underline"`. I put the bash indirection for the variables into one place so that I can replace that with an `eval` in the future to make tldr POSIX compliant, etc.

Anyway, you may want to diff my version against yours to make sure everything works as you'd expect.

Thanks for the PR, and your patience :-)

**Comment by ewels** [comment]
Fantastic stuff - thanks for finding the time! Super nice to get this merged and I agree with all of your tweaks 👍

**Pull request merged**
