### PR TITLE
Added option to create a local cache of files for offline access

### PR DESCRIPTION
**Pull request by becomesaflame**
Right now the script doesn't work if you're offline, unless you have read the tldr for that command before.  I added an option to download a copy of every command so that it will work reliably when offline.

### CODE REVIEW

**Comment by raylee** [comment]
I like this, and think the script should simply do this during the first invocation. But we can make this even better! As part of the official tldr build and release process, they generate a .zip bundle of all the pages, currently deployed here: https://tldr-pages.github.io/assets/tldr.zip

Could I convince you to make a small change to your PR and download the zip file version instead, placing all the files in the correct location?

For more details, please see https://github.com/tldr-pages/tldr/issues/569#issuecomment-168727611

**Comment by becomesaflame** [comment]
Good idea.  How would you feel about downloading the tarball instead of the zip?

**Comment by pepa65** [comment]
The advantage of using the zip file is that it's expressly made available for this purpose, and it also has the accompanying index.json file (because you want it to match):
https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/master/assets/tldr.zip

**Comment by raylee** [comment]
This has been resolved in a different pull request from @becomesaflame and Seth Woodworth. Thanks guys.

**Pull request closed without merging**
